version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: "install requirements"
      - run:
          command: pyinstaller --onefile main.py
          name: "generate cli exe with pyinstaller"
      - run:
          command: $ProgressPreference = "SilentlyContinue"; wget https://github.com/estuaryoss/estuary-agent-go/releases/download/4.2.0/estuary-agent-go.exe -O estuary-agent-go.exe
          name: "download estuary-agent"
      - run:
          command: $ProgressPreference = "SilentlyContinue"; wget https://github.com/estuaryoss/runcmd/releases/download/1.0.0/runcmd.exe -O runcmd.exe
          name: "download runcmd"
      - run:
          command: Start-Process .\estuary-agent-go.exe
          name: "start estuary-agent"
      - run:
          command: ping -n 5 127.0.0.1
          name: "wait some time"
      - run:
          command: python -m unittest discover tests "test_cli.py"
          name: "run integration tests"
      - run:
          command: Copy-Item "dist\main.exe" -Destination "main.exe"
          name: "copy main.exe"
      - store_artifacts:
          path: main.exe
workflows:
  main:
    jobs:
      - build-and-test
